---
title: "Sta 210 Final Project"
Team Members: "Ashley Lo, Adela Guo"
format: pdf
geometry: margin=2.5cm
---

```{r cleaning the dataset, message = F, warning = F, echo=FALSE, results = FALSE}
library(tidyverse) 
library(tidymodels)
library(MASS)
library(nnet)
library(car)
library(ggfortify)
library(naniar)

data_OG <- read.csv("Mental Health Tech CSV Cleaned.csv") 
data <- read.csv("Mental Health Tech CSV Cleaned.csv") 

data$"What.is.your.gender." <- tolower(data$"What.is.your.gender.")
data$"What.is.your.gender." <- str_trim(data$"What.is.your.gender.")

data$"What.is.your.gender."[data$"What.is.your.gender." == "female"] <- "f"
data$"What.is.your.gender."[data$"What.is.your.gender." == "male"] <- "m"

colnames(data)[1] ="self_employed"
colnames(data)[2] ="num_employees"
colnames(data)[3] ="company_focus"
colnames(data)[4] ="primary_role_tech"
colnames(data)[5] ="mental_health_covered"
colnames(data)[6] ="know_work_care_options"
colnames(data)[7] ="discussed_mental_health"
colnames(data)[8] ="resources_offered"
colnames(data)[9] ="anonymity_protected"
colnames(data)[10] ="difficulty_requesting_leave"

# Col K - P: Current workplace stigma
colnames(data)[11] ="mental_health_discussion_consequences"
colnames(data)[12] ="physical_health_discussion_consequences"
colnames(data)[13] ="comfort_discussing_with_coworkers"
colnames(data)[14] ="comfort_discussing_with_supervisor"
colnames(data)[15] ="as_serious_as_physical"
colnames(data)[16] ="observed_mental_health_consequences"

colnames(data)[17] ="have_mental_health_coverage"
colnames(data)[18] ="know_other_care_options"
colnames(data)[19] ="if_diagnosed_reveal_client"
colnames(data)[20] ="if_revealed_client_impact"
colnames(data)[21] ="if_diagnosed_reveal_coworker"
colnames(data)[22] ="if_revealed_coworker_impact"
colnames(data)[23] ="productivity_affected"
colnames(data)[24] ="if_productivity_affected_percent_affected"

# Col Y - AJ: Previous workplaces stigma
colnames(data)[25] ="prev_employers"
colnames(data)[26] ="if_prev_employers_mental_health_covered"
colnames(data)[27] ="if_prev_employers_know_work_care_options"
colnames(data)[28] ="if_prev_employers_discussed_mental_health"
colnames(data)[29] ="if_prev_employers_resources_offered"
colnames(data)[30] ="if_prev_employers_anonymity_protected"
colnames(data)[31] ="if_prev_employers_mental_health_discussion_consequences"
colnames(data)[32] ="if_prev_employers_physical_health_discussion_consequences"
colnames(data)[33] ="discuss_coworkers_previous"
colnames(data)[34] ="discuss_supervisor_previous"
colnames(data)[35] ="mentalphysical_previous"
colnames(data)[36] ="negative_consequence_coworkers_previous"

# AK - AS: Perceived societal stigma
colnames(data)[37] ="physical_interview"
colnames(data)[38] ="why_37"
colnames(data)[39] ="mental_interview"
colnames(data)[40] ="why_39"
colnames(data)[41] ="hurt_career"
colnames(data)[42] ="coworker_view_negatively"
colnames(data)[43] ="share_friends_families"
colnames(data)[44] ="unsupportive_response"
colnames(data)[45] ="observation_current"

colnames(data)[46] ="family_history"
colnames(data)[47] ="past_disorders"
colnames(data)[48] ="current_disorder"
colnames(data)[49] ="past_conditions_diagnosed"
colnames(data)[50] ="condition_believe"
colnames(data)[51] ="diagnoses"
colnames(data)[52] ="condition_diagnosed"
colnames(data)[53] ="seek_treatment"

# BB, BC: Work interference
colnames(data)[54] ="interfere_treated"
colnames(data)[55] ="interfere_not_treated"

# BD - BK: Demographic
colnames(data)[56] ="age"
colnames(data)[57] ="gender"
colnames(data)[58] ="country_live"
colnames(data)[59] ="USstate_live"
colnames(data)[60] ="country_work"
colnames(data)[61] ="USstate_work"
colnames(data)[62] ="work_position"
colnames(data)[63] ="remote_work"

replace_with_na_all(data, condition = ~.x == "")
data[data == ""] <- NA
#data$interfere_treated[data$interfere_treated == "Not applicable to me"] <- NA
data <- data[data$interfere_treated != "Not applicable to me", ]

```

```{r EDA: Summary Statistics, message = F, warning = F, echo=FALSE, out.width = "75%", out.height = "50%", fig.show="hold"}

library(gridExtra)
summary_plot <- ggplot(data, aes(x=reorder(interfere_treated, interfere_treated, function(x)-length(x)))) +
geom_bar(fill='magenta2') +  labs(x='response variable')
new_summary <- summary_plot + 
  theme(plot.title.position = "plot")

scatter_age_interference <- ggplot(data, aes(x = age, y = interfere_treated)) +
  geom_point() + geom_jitter(width = 15, height = 0.35) +
  labs(x = "Age",
       y = "Interference Frequency",
       title = 
      "Age Differences in 
       Work Interference 
       When Disorder 
       Treated")

grid.arrange(new_summary, scatter_age_interference, 
             ncol = 2, widths = c(0.38, 0.62))

```

```{r EDA: Demographic data, message = F, warning = F, echo=FALSE, out.width = "60%", out.height = "50%", fig.show="50%"}
library(ggmosaic)

mosaic_gender_interference <- ggplot(data = data) +
  geom_mosaic(aes(x = product(gender), fill = interfere_treated)) +   
  labs(y="Frequency of Work Interference", 
       x="Gender Identity", fill = "Interference Frequency",
       title = "Gender Differences in Work Interference 
       When Disorder is Treated") 

mosaic_remote_interference <- ggplot(data = data) +
  geom_mosaic(aes(x = product(remote_work), fill = interfere_treated)) +   
  labs(y="Frequency of Work Interference", 
       x="Remote Work Status", fill = "Interference Frequency",
       title = "Differences in Work Interference 
       When Disorder is Treated 
       Between Remote and Non-Remote Workers") 
mosaic_gender_interference
mosaic_remote_interference
```



```{r modelling missingness, message = F, warning = F, echo=FALSE, out.width = "75%", out.height = "55%", fig.show="hold"}
library(mice)
library(naniar)
library(UpSetR)

vis_miss(data, sort_miss = TRUE) + theme(text = element_text(size = 6))
```

```{r creating the model, message = F, warning = F, echo=FALSE,out.width = "50%", out.height = "50%"}
library(MASS)
library(sure)
m1 <- polr(ordered(data$interfere_treated, levels = c("Never", "Rarely", 
                                                      "Sometimes", "Often")) 
           ~ physical_interview + mental_interview 
           + hurt_career + coworker_view_negatively + share_friends_families 
           + physical_interview*mental_interview 
           + age, data = data)

#output <- tidy(m1)
#cat('<div style="font-size: 10px">')
#print(output)
#cat('</div>')

summary(m1)

m2 <- polr(as.factor(interfere_treated) ~ 1, data = data)

output <- anova(m2, m1)
cat('<div style="font-size: 10px">')
print(output)
cat('</div>')

```

```{r assessing linearity, message = F, warning = F, echo=FALSE, out.width = "50%", out.height = "50%", fig.width="85%"}
library(Stat2Data)
emplogitplot1(as.factor(interfere_treated) ~ age,
              data = data,
              ngroups = "all")
```
